#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a  desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config normal_border_color "#333333"
bspc config active_border_color "#ff0000"
bspc config focused_border_color "#ff0000"
bspc config presel_feedback_color "#ff0000"
export SUN_AWT_NO_ERASEBACKGROUND=1

xrandr --newmode "1920x1080_120.00" 369.50 1920 2080 2288 2656 1080 1083 1088 1160 -hsync +vsync
xrandr --addmode None-1 "1920x1080_120.00"
xrandr --output None-1 --mode "1920x1080_120.00"
feh --bg-center /home/Avilx/wallpapers/blackarch.png &
